### ISSUE TITLE
when sorting / searching the count of devices is not dynamically changing.

### ISSUE THREAD

**Issue by thorleifjacobsen** [realvnc-labs/rport#1013]
When sorting by e.g. `disconnected` the count for client groups or `All` does not update. It shows the total even though there are only 10-20 disconnected.

![image](https://user-images.githubusercontent.com/8550684/232010597-adec7581-4382-4067-8781-30e3719aaeb8.png)

**Comment by thorstenkramm** [comment]
This has been fixed in the latest version 0.9.12
