### ISSUE TITLE
Rportd 0.9.10 with Frontend 0.9.11 + RportPlus oauth login results in endless loop 

### ISSUE THREAD

**Issue by trafagdim** [realvnc-labs/rport#1015]
**Oauth Login did not work on 0.9.11 frontend**
Unstable Rportd verison 0.9.10 with Frontend 0.9.11 using the RportPlus plugin  `rport-plus_0.3.0@0.9.10_Linux_x86_64.tar.gz` results in non function oauth login. After the pressing der Button "Login with Microsoft" the Login Azue Procedure apears and the login is successul. The call back URL redirects afterwarts to the initial auth screen instead to the dashboard. No error ist prompted.
The authentication ist so stuck in an endless loop.  

In case you know it. Is the bug related to `rportd` (server) or `rport` (client)? server

**Environment**
Describe the environment where the bug occurs:

* RPort version 0.9.10 / Forntend `rport-frontend-0.9.11-build-1125`
* OS Linux Debian Bookworm
* Is rportd running inside a docker container? No
* Are you using a reverse proxy? If yes, which one? No
* RportPlus plugin  `rport-plus_0.3.0@0.9.10_Linux_x86_64.tar.gz`
* Oauth with Mircrosoft Azure

Using the Frontend `rport-frontend-0.9.6-build-1133` the oauth authentication works with the same setup.

**Comment by trafagdim** [comment]
Issue exists also in RPort Version 0.9.11 and `rport-plus_0.3.0@0.9.11_Linux_x86_64.tar.gz`

**Comment by thorstenkramm** [comment]
@trafagdim Thanks for reporting. But this is expected. The 0.9.6 and also 0.9.11 frontend does not support oAuth yet.

**Comment by trafagdim** [comment]
@thorstenkramm  I dont have found any notes about this limitation of the prerelease version in the documentaion
https://plus.rport.io/auth/oauth-introduction/
We use oauth succesfull in the stable version 0.9.5, is there any plans to implentent to fix the oauth in one of the next prerelease versions?
