### ISSUE TITLE
Saved tunnels disappear after 5 minutes - v 0.9.12

### ISSUE THREAD

**Issue by RichardBurt65** [realvnc-labs/rport#1039]
**Describe the bug**
Windows client with saved SSH tunnels. After 5 minutes the tunnels disappear and need to be recreated. 

Recreating the tunnels end up with previous tunnels then reappearing. Trying to delete any of the tunnels shows "Tunnel could not be terminated" error message (see screenshot)

**Environment**
Server - Digital Ocean Debian 10 fresh install today. Endpoint -  Windows 11. 

* RPort version - 0.9.12
* OS details - Debian 10 and Windows 11
* Is rportd running inside a docker container? No
* Are you using a reverse proxy? If yes, which one? No

**Log file**
Log files attached. 

[rport.log](https://github.com/realvnc-labs/rport/files/11485361/rport.log)
[rportd.log](https://github.com/realvnc-labs/rport/files/11485362/rportd.log)
<img width="1512" alt="Screenshot 2023-05-16 at 11 54 24" src="https://github.com/realvnc-labs/rport/assets/110833650/626099d5-abd9-4019-8709-9b0d3c25a26c">

**Comment by thorstenkramm** [comment]
@RichardBurt65 
Did you deactivate the "Auto Close" option on tunnel creation?
<img width="913" alt="image" src="https://github.com/realvnc-labs/rport/assets/16852023/a6ea61f8-ed32-42d4-a6bd-3db1597f162e">

**Comment by RichardBurt65** [comment]
Yes

**Comment by thorstenkramm** [comment]
Bug confirmed. Removing the checkbox submits `/api/v1/clients/f7f72ad22c6042a1a214ae0e1968c35f/tunnels?remote=22&scheme=ssh&acl=1234&idle-timeout-minute=1&protocol=tcp` where `idle-timeout-minute=N` must be omitted entirely.

**Comment by RichardBurt65** [comment]
So how to remove current tunnels? (quite happy to reinstall from scratch if it's going to be quicker).

**Comment by thorstenkramm** [comment]
@RichardBurt65 If the tunnel has been terminated by inactivity, just hit reload and it disappears from the list. No need to delete.

**Comment by RichardBurt65** [comment]
Tried that already. They are still listed.

**Comment by thorstenkramm** [comment]
@RichardBurt65 If you make the browser window wider, the delete tunnel button should appear. 
<img width="757" alt="image" src="https://github.com/realvnc-labs/rport/assets/16852023/d3d3ab28-9277-42f0-94f5-717979893aae">

**Comment by RichardBurt65** [comment]
<img width="1512" alt="Screenshot 2023-05-16 at 13 03 30" src="https://github.com/realvnc-labs/rport/assets/110833650/847bdc14-125f-4a76-abf5-4d9f636d1d56">

**Comment by thorstenkramm** [comment]
@RichardBurt65 Try with Edge, Chrome, FF. Safari support is mainly broken.

**Comment by RichardBurt65** [comment]
Not my preferred browsers but it does show me the delete button and then back to "Tunnel could not be terminated" error message.

I'll scrub the server and reinstall from scratch - and forget about creating tunnels until a fix is confirmed.

**Comment by thorstenkramm** [comment]
@RichardBurt65 We are fixing all Safari issues. Re-Installing the server will not solve any of your issues because it's frontend related. You must wait for an update. Hopefully published within a few days.

**Comment by thorstenkramm** [comment]
@RichardBurt65 If you go to the Tunnel overview, the delete button is present on Safari.
<img width="1603" alt="image" src="https://github.com/realvnc-labs/rport/assets/16852023/25fa9944-7828-41ba-8d2d-14218e2b1e85">

**Comment by eksalih** [comment]
some buttons are not visible for Example image attached here 
![image](https://github.com/realvnc-labs/rport/assets/69579940/2f544d08-0ccc-491c-86ef-5105625e4f4c)

**Comment by RichardBurt65** [comment]
Confirmed and many thanks.
