### ISSUE TITLE
0.9.12 UI bugs (macOS Safari and Microsoft Edge)

### ISSUE THREAD

**Issue by RichardBurt65** [realvnc-labs/rport#1040]
At the "delete tunnel" stage the dialogue box is missing. 

<img width="1512" alt="Screenshot 2023-05-16 at 12 19 08" src="https://github.com/realvnc-labs/rport/assets/110833650/b0dd4978-a8f4-4b97-9553-fb9f5c3bde20">

**Comment by eksalih** [comment]
the same for me in Windows i am using Chrome but am able to terminate the session using the 3dots  button and delete

**Comment by thorstenkramm** [comment]
Try updating the frontend to the latest version, which contains many fixes.
Download [frontend 0.9.12-1](https://download.rport.io/frontend/stable/rport-frontend-0.9.12-1-build-1129.zip) and replace the files in `/var/lib/rport/docroot` with the files from ZIP file.

```
cd /tmp
wget https://download.rport.io/frontend/stable/rport-frontend-0.9.12-1-build-1129.zip
sudo -u rport sh -c "cd /var/lib/rport/docroot; unzip -o /tmp/rport-frontend-0.9.12-1-build-1129.zip"
rm rport-frontend-0.9.12-1-build-1129.zip
```
 
Hard reload (Shift-Reload) your browser. _No need to restart the rport server._

🙏 Much appreciated if you confirm your issue has been solved by the update.
