### ISSUE TITLE
There is Bug i noticed on the UI

### ISSUE THREAD

**Issue by eksalih** [realvnc-labs/rport#1041]
here i noticed one Bug
When we select theme as Dark mode the dropdown list gets blank (empty) and when we hover mouse over the place it will appear.
other than that, on last version we had a option to change the side bar to top/left that is no longer there. and the UI is not fit when you are in Inventory page or Client's page

![image](https://github.com/realvnc-labs/rport/assets/69579940/0fabe88f-bd0f-4b8d-bcc1-f4e35561a53f)

![image](https://github.com/realvnc-labs/rport/assets/69579940/8daa092a-175d-43b2-b3e5-577ffd30dd43)

**Comment by thorstenkramm** [comment]
@eksalih 
Which browser and OS is it?
I can't reproduce with Chrome or FF.
<img width="634" alt="image" src="https://github.com/realvnc-labs/rport/assets/16852023/ad376ecd-1717-4bdf-98ac-85e044f1c69f">

**Comment by thorstenkramm** [comment]
@eksalih I can confirm the dark theme is partially broken on Windows. Please switch to the light theme while we are working on an update.

**Comment by thorstenkramm** [comment]
Try updating the frontend to the latest version, which contains many fixes.
Download [frontend 0.9.12-1](https://download.rport.io/frontend/stable/rport-frontend-0.9.12-1-build-1129.zip) and replace the files in `/var/lib/rport/docroot` with the files from ZIP file.

```
cd /tmp
wget https://download.rport.io/frontend/stable/rport-frontend-0.9.12-1-build-1129.zip
sudo -u rport sh -c "cd /var/lib/rport/docroot; unzip -o /tmp/rport-frontend-0.9.12-1-build-1129.zip"
rm rport-frontend-0.9.12-1-build-1129.zip
```
 
Hard reload (Shift-Reload) your browser. _No need to restart the rport server._

🙏 Much appreciated if you confirm your issue has been solved by the update.
