### ISSUE TITLE
0.9.12 Unable to save scripts

### ISSUE THREAD

**Issue by RichardBurt65** [realvnc-labs/rport#1045]
<img width="1512" alt="Screenshot 2023-05-17 at 08 03 52" src="https://github.com/realvnc-labs/rport/assets/110833650/d04a9e96-c3f2-45d3-9f3f-b064bb271a7d">

**Comment by csetuomas** [comment]
I have same problem

**Comment by thorstenkramm** [comment]
Try updating the frontend to the latest version, which contains many fixes.
Download [frontend 0.9.12-1](https://download.rport.io/frontend/stable/rport-frontend-0.9.12-1-build-1129.zip) and replace the files in `/var/lib/rport/docroot` with the files from ZIP file.

```
cd /tmp
wget https://download.rport.io/frontend/stable/rport-frontend-0.9.12-1-build-1129.zip
sudo -u rport sh -c "cd /var/lib/rport/docroot; unzip -o /tmp/rport-frontend-0.9.12-1-build-1129.zip"
rm rport-frontend-0.9.12-1-build-1129.zip
```
 
Hard reload (Shift-Reload) your browser. _No need to restart the rport server._

🙏 Much appreciated if you confirm your issue has been solved by the update.

**Comment by RichardBurt65** [comment]
Not fixed.
