### ISSUE TITLE
No Login possible

### ISSUE THREAD

**Issue by bloesss** [realvnc-labs/rport#1048]
After Updating Rportd with the Update Script, I cannot login anymore.
It just does nothing when I try, goes back to login screen. 

The Update seems to have installed 0.9.12, I did not think about, because it is no stable version.
How can I downgrade?

**Comment by thorstenkramm** [comment]
@bloesss Are you using TOTP?

**Comment by bloesss** [comment]
No, I am using the default rport authentification.

Problem will be that the GUI doesnt work with 0.9.12, so I need to downgrade to 0.9.5

Or you finally bring me 1.0.0 ;)

**Comment by thorstenkramm** [comment]
@bloesss Try updating the frontend to the latest version, which contains many fixes.
Download [frontend 0.9.12-1](https://download.rport.io/frontend/stable/rport-frontend-0.9.12-1-build-1129.zip) and replace the files in `/var/lib/rport/docroot` with the files from ZIP file. 
Refresh (Shift-Reload) your browser. No need to restart the rport server.

**Comment by bloesss** [comment]
I did. The UI looks nice but seems crappy.
For example, I can only see 22 Client Groups in the overview. Alphabetical ends with "c".
No Option to see more. In the inventory i can see all clients of all groups. The groups also exist.

**Comment by bloesss** [comment]
And in the Mobile View, I can't do anything but changing my own setup.
No Buttons, No Clients, Nothing. 0.9.5 was not optimal but at least I had a change, if I had a lot of patience, to start an rdp session

**Comment by bloesss** [comment]
I have created a new topic.
As I can login, this can be closed.
