### ISSUE TITLE
Many Problems with Web GUI 0.9.12-1-build-1129

### ISSUE THREAD

**Issue by bloesss** [realvnc-labs/rport#1049]
I accidentily updated the Server to 0.9.12 and updated the gui.
The GUI looks much more modern, thats nice. But it is unusable for us. Everything was done as administrator:

1) In the overview, I can only see the first 22 Client Groups, sorted alphabetically. If I create a group "1234", the last group in the list disappears.

2) In the Mobile View, You can't do nothing. The old 0.9.5 GUI was very, very, very complicated on mobile phones but I at least had a chance to start a tunnel in case of emergency. In the new GUI, everything ist gone, not clients, no groups, nothing. Just the ability to setup my account

3) If I want to start a tunnel, now I have to first click the three dots to open a menu where I can start or delete the tunnel. That is very complicated. In the old GUI, it was just one Click. Sounds not important, but it is absolutely no fun swapping between tunnels that way. For example, if I stored the tunnel, I could always connect with to clicks: 1) Start the Tunnel, 2) Connect the Tunnel. Now it is 4 Steps. Choose Tunnel, start tunnel, choose started Tunnel, connect tunnel.

4) If I Click the rport logo in the upper left corner, I always get to the Welcome Screen with the Plug Animation. No matter if I choose "don't show this again". In 0.9.5, it brought be to the main dashboard. The Plug Animation does not make any sense, I don't see a reason why this shows up.

**Comment by bloesss** [comment]
Thank you. But not having a chance to create a connection on my mobile phone is a No-Go at the moment.
I think we should downgrade at this point.

**Comment by bloesss** [comment]
Another Problem:

If the script is longer than the script Window, the script seems to be over the window and I can't click "execute" anymore.
The Scroll Bars are missing.

![image](https://github.com/realvnc-labs/rport/assets/115469103/a51fbcdc-1c82-4758-ada0-d555894c8c9f)

**Comment by bloesss** [comment]
Now, the cookie informations seem to get lost every often.
All settings are gone and I need to login twice in an hour.

**Comment by bloesss** [comment]
Then I do a "dir" command, every line gets a TAB:

![image](https://github.com/realvnc-labs/rport/assets/115469103/7928bd86-5b08-41ec-bf13-7652d0214252)

**Comment by rdeago** [comment]
> 4. If I Click the rport logo in the upper left corner, I always get to the Welcome Screen with the Plug Animation. No matter if I choose "don't show this again".

This also affects desktop browsers (Edge in my case, but I suspect it's not a browser-specific issue).

**Comment by bloesss** [comment]
> > 7\. If I Click the rport logo in the upper left corner, I always get to the Welcome Screen with the Plug Animation. No matter if I choose "don't show this again".
> 
> This also affects desktop browsers (Edge in my case, but I suspect it's not a browser-specific issue).

It isnt Browser specific. It's Just Viewport CSS.

**Comment by MarcSamD** [comment]
@thorstenkramm 
Also the inventory page should be improved:
1. The table is not responsive and a lot of space is lost on both side for wide screens
2. There is no horizontal scrollbar to see columns not displayed on the right (must use mouse highlight and drag right)

![image](https://github.com/realvnc-labs/rport/assets/70358310/8ff42a46-8554-4349-9cf3-70de67b07829)

**Comment by thorstenkramm** [comment]
🙇 Apologies for having released such a buggy version of the RPort UI.
Try updating the frontend to the latest version [frontend 0.9.12-3](https://download.rport.io/frontend/stable/) or newer, which contains a fix for almost all described issues except the mobile view. A better mobile view will be released in a few days. We are working on it.


```
curl -L https://download.rport.io/frontend/stable/latest.php -o /tmp/rport-frontend-latest.zip
sudo -u rport sh -c "cd /var/lib/rport/docroot; unzip -o /tmp/rport-frontend-latest.zip"
rm /tmp/rport-frontend-latest.zip
```
 
Hard reload (Shift-Reload) your browser. _No need to restart the rport server._

🙏 Much appreciated if you confirm your issue has been solved by the update.

**Comment by MarcSamD** [comment]
rport-frontend-0.9.12-3-build-1131

1 & 2 not tested
3 & 4 seems solved
5 & 6 still not ok

**Comment by bloesss** [comment]
Thank you I will try.
We waited with the downgrade

**Comment by bloesss** [comment]
1) Is solved. But we have a lot of Groups. If you want to see Group "Z", you have to push the button a lot. Very frustrating. The old solution was much better without needing that button. At least, it seems usable again.
2) I still can't do anything but looking at my own profile in the mobile view.
3) Still the same. As Point 1, the Usability did not win with the update. Much too complicated.
4) The rport Logo has no function at all after the update. That's better, because you don't accidentily open the "Welcome" Screen with every second click. But I think it should lead you to the dashboard.

**Comment by thorstenkramm** [comment]
@bloesss The new frontend was needed to manage large environments (> 10k clients). 
The old frontend did load all clients and all client groups into the browsers' memory. This doesn't scale. 
Now small junks are loaded and pagination is used everywhere. 

> Isn't there really any trick to use the old dashboard with new rportd?

No. I'm sorry. All features and bug fixes will be done on the new UI only. And for the above reason we had to discontinue the old version. 

As mentioned: A mobile-optimized version is underway. 

Regarding the "load more" button on the client groups, we will think about a better pagination, so you can jump to a specific range directly.

**Comment by bloesss** [comment]
> @bloesss The new frontend was needed to manage large environments (> 10k clients). The old frontend did load all clients and all client groups into the browsers' memory. This doesn't scale. Now small junks are loaded and pagination is used everywhere.
> 
> > Isn't there really any trick to use the old dashboard with new rportd?
> 
> No. I'm sorry. All features and bug fixes will be done on the new UI only. And for the above reason we had to discontinue the old version.
> 
> As mentioned: A mobile-optimized version is underway.
> 
> Regarding the "load more" button on the client groups, we will think about a better pagination, so you can jump to a specific range directly.

Thank you. We had a test Environment with 98 Groups and 900 Clients. The old UI performed well and the pagination was never needed. I would really like to have the choice to have a simple scroll bar as it was before.

A new Problem: I can't delete any opened Tunnel. have to wait until they delete themselves.

**Comment by thorstenkramm** [comment]
We released an update. 
Try updating the frontend to the latest version [frontend 0.9.12-4](https://download.rport.io/frontend/stable/) or newer, which contains a fix for the above issues except mobile view.


```
curl -L https://download.rport.io/frontend/stable/latest.php -o /tmp/rport-frontend-latest.zip
sudo -u rport sh -c "cd /var/lib/rport/docroot; unzip -o /tmp/rport-frontend-latest.zip"
rm /tmp/rport-frontend-latest.zip
```
 
Hard reload (Shift-Reload) your browser. _No need to restart the rport server._

This issue must be closed because too many issues have been mixed. If something is still broken, please create a new issue. One issue per topic! Don't mix.

**Comment by bloesss** [comment]
> We released an update. Try updating the frontend to the latest version [frontend 0.9.12-4](https://download.rport.io/frontend/stable/) or newer, which contains a fix for the above issues except mobile view.
> 
> ```
> curl -L https://download.rport.io/frontend/stable/latest.php -o /tmp/rport-frontend-latest.zip
> sudo -u rport sh -c "cd /var/lib/rport/docroot; unzip -o /tmp/rport-frontend-latest.zip"
> rm /tmp/rport-frontend-latest.zip
> ```
> 
> Hard reload (Shift-Reload) your browser. _No need to restart the rport server._
> 
> This issue must be closed because too many issues have been mixed. If something is still broken, please create a new issue. One issue per topic! Don't mix.

If you're interested, I deleted the ".hidden" directive in /var/lib/rport/docroot/_nuxt/entry.1b3d473c.css.
And now everything works fine in mobile view with the latest release (today) of the rport gui.
