### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by brunodiias** [realvnc-labs/rport#1054]
In a new installation of rport server in 0.9.12 release, all MS Windows clients created and installed by script don't connect to service.

The log report show this:
2023/05/18 11:40:17 error: client: connection error: client is already connected or previous session was not properly closed (attempt: 6 of infinite)
2023/05/18 11:40:17 info: client: Server will clean up orphaned sessions within its {check_clients_connection_interval} automatically.

**Comment by thorstenkramm** [comment]
@brunodiias Check your system IDs. Very likely they are duplicated.
https://kb.rport.io/need-help/troubleshoot-common-problems/id-is-already-in-use
Consider switching to manually created system IDs.

If this doesn't solve your issue, please re-open.
