### ISSUE TITLE
The tunnel never opens due to a bug

### ISSUE THREAD

**Issue by qraleq** [realvnc-labs/rport#1055]
Hi, we've noticed an issue where the tunnel never opens with the following settings on `rport-frontend-0.9.12-1-build-1129`:

![2023-05-19-09-18-51](https://github.com/realvnc-labs/rport/assets/13619177/8649a8bb-6a4e-41c5-a95f-30a97ca05a83)

An error is thrown in the browser console:
```
entry.2dd244c5.js:1 TypeError: Cannot read properties of undefined (reading 'replace')
    at ze (_slug_.ecdf647b.js:1:11734)
    at Qe (_slug_.ecdf647b.js:1:11309)
    at entry.2dd244c5.js:1:108342
    at callWithErrorHandling (entry.2dd244c5.js:1:19892)
    at callWithAsyncErrorHandling (entry.2dd244c5.js:1:20014)
    at HTMLFormElement.r (entry.2dd244c5.js:1:92635)
logError @ entry.2dd244c5.js:1
handleError @ entry.2dd244c5.js:1
(anonymous) @ entry.2dd244c5.js:1
Promise.catch (async)
callWithAsyncErrorHandling @ entry.2dd244c5.js:1
r @ entry.2dd244c5.js:1
```

It seems that some parameter handling is not done properly. 

Thank you!

**Comment by thorstenkramm** [comment]
@qraleq Thanks for reporting. I can confirm the bug. If no acl is set, the frontend does not dispatch any request. A fix is underway.

**Comment by SuperKali** [comment]
i can confirm i have the same problem

**Comment by SuperKali** [comment]
@thorstenkramm Hi thank you for release a new version, I appreciate it.

All seems work fine, I noticed a problem, if the connection is opened with the client, I can’t delete the tunnel.

it is a bug?

regards.

**Comment by SuperKali** [comment]
another issue is this:

<img width="1208" alt="image" src="https://github.com/realvnc-labs/rport/assets/19473898/f9782d79-6337-40d6-9eb7-08276dbf9589">

I can't set only minutes
