### ISSUE TITLE
Command / script output invisible in dark mode

### ISSUE THREAD

**Issue by rdeago** [realvnc-labs/rport#1057]
**Describe the bug**

When using dark mode, for example in MS Edge, command / script output is white text on a white background.

**Environment**

RPort version 0.9.12 running on Debian 11.6/x64.

**Log file**

Not relevant.

**Screenshots**

This is after executing command `ls -la /etc` on a client.

Light mode:
![Light mode](https://github.com/realvnc-labs/rport/assets/139223/dce26de6-8759-46b7-a841-79d43e8552ff)

Dark mode:
![Dark mode](https://github.com/realvnc-labs/rport/assets/139223/d9abe5e3-d197-4ef1-992a-d4a62956aa83)

**Comment by thorstenkramm** [comment]
🙇 Apologies for having released such a buggy version of the RPort UI.
Try updating the frontend to the latest version [frontend 0.9.12-3](https://download.rport.io/frontend/stable/) or newer, which contains a fix for this issue.


```
curl -L https://download.rport.io/frontend/stable/latest.php -o /tmp/rport-frontend-latest.zip
sudo -u rport sh -c "cd /var/lib/rport/docroot; unzip -o /tmp/rport-frontend-latest.zip"
rm /tmp/rport-frontend-latest.zip
```
 
Hard reload (Shift-Reload) your browser. _No need to restart the rport server._

🙏 Much appreciated if you confirm your issue has been solved by the update.
