### ISSUE TITLE
0.9.12 web interface at "User Groups" section is missing the Add Button

### ISSUE THREAD

**Issue by marcus365** [realvnc-labs/rport#1058]
At 0.9.12 interface there is a missing "Add" button inside the "User Groups" section.
![Capture](https://github.com/realvnc-labs/rport/assets/133788691/7bbd5e8e-703c-4625-b916-c88dc185021d)

**Comment by thorstenkramm** [comment]
@marcus365 I think it's not missing. 
There is a hint "New user groups are created from the user administration".
Just go to a user and add it to a new group, and it will appear in the user groups administration.

**Comment by marcus365** [comment]
I just know that from .0.9.5 web interface. But at 0.9.12 at the new User under Groups we can't type anymore for creating the new group.




Marcus Tse

[fdfsdf]

IT Consulting Specialist

T:  (647)-495-6963

***@***.***>@***@***.***>



Notice: The Information contained in this transmission is privileged and confidential and intended only for the use of the individual or entity to whom it is addressed. If you are not the intended recipient, you are hereby notified that any distribution, copying, disclosure or taking of any action in reliance on the contents of this transmission is strictly prohibited and review by any individual other than the intended recipient shall not constitute waiver of privilege. If you have received this transmission in error, please notify us immediately and delete the original transmission. Thank you.

________________________________

**Comment by thorstenkramm** [comment]
@marcus365 Damn. You are right. We will fix this ASAP.

**Comment by thorstenkramm** [comment]
🙇 Apologies for having released such a buggy version of the RPort UI.
Try updating the frontend to the latest version [frontend 0.9.12-3](https://download.rport.io/frontend/stable/) or newer, which contains a fix for this issue.


```
curl -L https://download.rport.io/frontend/stable/latest.php -o /tmp/rport-frontend-latest.zip
sudo -u rport sh -c "cd /var/lib/rport/docroot; unzip -o /tmp/rport-frontend-latest.zip"
rm /tmp/rport-frontend-latest.zip
```
 
Hard reload (Shift-Reload) your browser. _No need to restart the rport server._

🙏 Much appreciated if you confirm your issue has been solved by the update.

**Comment by marcus365** [comment]
Thanks. Let me try.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by thorstenkramm** [comment]
@marcus365 After typing in the new group name, did you confirm by hitting enter?

**Comment by marcus365** [comment]
yes. I did try press enter after i enter the new group name and the new group name disappear and also no show at the drop down too.
Also i did type the new group name and press save to create the user. The use created but no new group create.




Marcus Tse

[fdfsdf]

IT Consulting Specialist

T:  (647)-495-6963

***@***.***>@***@***.***>



Notice: The Information contained in this transmission is privileged and confidential and intended only for the use of the individual or entity to whom it is addressed. If you are not the intended recipient, you are hereby notified that any distribution, copying, disclosure or taking of any action in reliance on the contents of this transmission is strictly prohibited and review by any individual other than the intended recipient shall not constitute waiver of privilege. If you have received this transmission in error, please notify us immediately and delete the original transmission. Thank you.

________________________________

**Comment by thorstenkramm** [comment]
@marcus365 Which frontend version, which browser, which operating system?

**Comment by marcus365** [comment]
after reboot the rport server now i can see the frontend is rport-frontend-0.9.12-3-build-1131




Marcus Tse

[fdfsdf]

IT Consulting Specialist

T:  (647)-495-6963

***@***.***>@***@***.***>



Notice: The Information contained in this transmission is privileged and confidential and intended only for the use of the individual or entity to whom it is addressed. If you are not the intended recipient, you are hereby notified that any distribution, copying, disclosure or taking of any action in reliance on the contents of this transmission is strictly prohibited and review by any individual other than the intended recipient shall not constitute waiver of privilege. If you have received this transmission in error, please notify us immediately and delete the original transmission. Thank you.

________________________________

**Comment by marcus365** [comment]
It still not working and the latest version frontend 0.9.12.4 is not allow to type in the group again.




Marcus Tse

[fdfsdf]

IT Consulting Specialist

T:  (647)-495-6963

***@***.***>@***@***.***>



Notice: The Information contained in this transmission is privileged and confidential and intended only for the use of the individual or entity to whom it is addressed. If you are not the intended recipient, you are hereby notified that any distribution, copying, disclosure or taking of any action in reliance on the contents of this transmission is strictly prohibited and review by any individual other than the intended recipient shall not constitute waiver of privilege. If you have received this transmission in error, please notify us immediately and delete the original transmission. Thank you.

________________________________
