### ISSUE TITLE
Inline filtering instead of a filter modal

### ISSUE THREAD

**Issue by qraleq** [realvnc-labs/rport#1061]
In frontend versions prior to rport-frontend-0.9.12, there was an option to do inline filtering instead of having to open a modal. In those versions, opening a filter modal was optional, and we found it to be a much better option since you don't lose the context of the sidebar. 

 
![image](https://github.com/realvnc-labs/rport/assets/13619177/8064a1a9-f921-40e4-9f99-bf661d38f268)

Previously, clicking on the filter button opened the modal, now if you click anywhere it opens the modal.
![image](https://github.com/realvnc-labs/rport/assets/13619177/a2eb2f4d-fd85-4bff-9ec5-53b176d32056)

Did you change this behavior on purpose, or it is just missing in the new version?
Is there a way to support the old behavior?

**Comment by thorstenkramm** [comment]
@qraleq 
Your request has been integrated into the latest version of the frontend. 

Try updating the frontend to the latest version [frontend 0.9.12-5](https://download.rport.io/frontend/stable/) or newer, which contains a fix for this issue.


```
curl -L https://download.rport.io/frontend/stable/latest.php -o /tmp/rport-frontend-latest.zip
sudo -u rport sh -c "cd /var/lib/rport/docroot; unzip -o /tmp/rport-frontend-latest.zip"
rm /tmp/rport-frontend-latest.zip
cat /var/lib/rport/docroot/version.txt
```
 
Hard reload (Shift-Reload) your browser. _No need to restart the rport server._
