### ISSUE TITLE
Buggy client filtering on Commands and Scripts

### ISSUE THREAD

**Issue by qraleq** [realvnc-labs/rport#1066]
In versions prior to the newest frontend version (rport-frontend-0.9.12-3-build-1131), the filtering functionality on the Commands and Scripts pages worked really well. Now, we're seeing very inconsistent behavior when typing some expression to filter by:

![image](https://github.com/realvnc-labs/rport/assets/13619177/5d46e927-d902-4aa8-9ca6-b391da491454)

Unfortunately, the expression doesn't seem to be evaluated at all, so no matching is done.  
Also, it doesn't automatically select all the clients, and there's no way to select all clients that match the expression. If you have hundreds of devices, it's not really useful.
 
We would appreciate it if you could test this a bit more and re-introduce the behavior that was really good before the update.

Thank you!

**Comment by bloesss** [comment]
> In versions prior to the newest frontend version (rport-frontend-0.9.12-3-build-1131), the filtering functionality on the Commands and Scripts pages worked really well. Now, we're seeing very inconsistent behavior when typing some expression to filter by:
> 
> ![image](https://user-images.githubusercontent.com/13619177/240662096-5d46e927-d902-4aa8-9ca6-b391da491454.png)
> 
> Unfortunately, the expression doesn't seem to be evaluated at all, so no matching is done. Also, it doesn't automatically select all the clients, and there's no way to select all clients that match the expression. If you have hundreds of devices, it's not really useful.
> 
> We would appreciate it if you could test this a bit more and re-introduce the behavior that was really good before the update.
> 
> Thank you!

Additional, I recognized that I cannot chose the bottom Groups in the Filter List.
The List of Groups seems to be bigger than the Windows, So I have no Access to Groups I called "z-firewall" and so on.
So at the Moment, I cannot schedule Updates.

**Comment by thorstenkramm** [comment]
@bloesss 

🙇 Apologies for having released such a buggy version of the RPort UI.
Try updating the frontend to the latest version [frontend 0.9.12-5](https://download.rport.io/frontend/stable/) or newer, which contains a fix for this issue.


```
curl -L https://download.rport.io/frontend/stable/latest.php -o /tmp/rport-frontend-latest.zip
sudo -u rport sh -c "cd /var/lib/rport/docroot; unzip -o /tmp/rport-frontend-latest.zip"
rm /tmp/rport-frontend-latest.zip
cat /var/lib/rport/docroot/version.txt
```
 
Hard reload (Shift-Reload) your browser. _No need to restart the rport server._

🙏 Much appreciated if you confirm your issue has been solved by the update.

**Comment by qraleq** [comment]
Hi @thorstenkramm , this is working much better now, but it's still missing an important part of the functionality.
Before, we were able to select all the clients that matched the filters which was very convenient.
Can you please add select all option in the new version as well?

Something like this:
![image](https://github.com/realvnc-labs/rport/assets/13619177/d37c7cc6-80de-497c-b17a-4ee702c8b8ea)
