### ISSUE TITLE
UI: table regression after frontend update to 0.9.12

### ISSUE THREAD

**Issue by MarcSamD** [realvnc-labs/rport#1068]
**Describe the bug**
After upgrading to 0.9.12, the table display is less convenient.
Same issues for all the pages sharing the same table, i.e.: Tunnels, Inventory, Schedules, Audits
But in my case I'm mostly impacted on Inventory page as it has the higher number of rows (despite I have only 8 rows).

1. The table is not responsive and a lot of space is lost on both side for wide screens,
2. The scrollbars are a bit narrow so not very convenient to click,
3. The scrollbars are displayed even when it is not needed (in my case issue for inventory page only, refer to screenshot below),
4. The table columns customization is not preserved (at least after 24h).

**Environment**
rport-frontend-0.9.12-4-build-1132

**Screenshots**
Current display:
![Current display](https://github.com/realvnc-labs/rport/assets/70358310/d0e22bb8-8ded-421f-9174-a614b03143eb)

Expected display:
![Expected display](https://github.com/realvnc-labs/rport/assets/70358310/01400cf2-4f59-48bc-bed0-5ab045c5a9e1)

**CSS modified**
/!\ This has not been thoroughly tested, only browser edit on dev tools.
1.  Remove `max-w-7xl` in `class="mx-auto h-screen max-h-screen max-w-7xl px-4 py-10 sm:px-6 lg:px-8 lg:py-12"`
2. Increase from 6px to 10px in `::-webkit-scrollbar {height: 6px; width: 6px;}`
3. tbd
4. tbd

**Comment by MarcSamD** [comment]
For reference, no scrolbar at all in latest update rport-frontend-0.9.12-5-build-1133

**Comment by thorstenkramm** [comment]
@MarcSamD It's relatively thin, but the scrollbar is there.

https://github.com/realvnc-labs/rport/assets/16852023/e7f000ef-3f8f-4f62-86d3-e3956c2c77ca

**Comment by MarcSamD** [comment]
Hi @thorstenkramm, 
Thank you for the video, I'm using Microsoft Edge Version 113.0.1774.57 and indeed there is a scrollbar but in my case it is completely invisible:
![image](https://github.com/realvnc-labs/rport/assets/70358310/e6a5e497-c81e-4d24-a468-7b4c403209a9)

It seems hidden by the block showing the number of results.
By removing the `div class="shadow-b border border-gray-100 ring-1 ring-black ring-opacity-5 dark:border-slate-700 sm:rounded-b-lg mb-12 h-[54px] bg-gray-50 dark:bg-gray-950"` it will appear:
![image](https://github.com/realvnc-labs/rport/assets/70358310/58e3ae26-d0ae-4a7f-88e2-f13e127d9316)

**Comment by MarcSamD** [comment]
I confirm that the issues "scrollbar not displayed" and "scrollbars are displayed even when it is not needed" have been solved in rport-frontend-0.9.12-6-build-1134.
I have opened dedicated threads for the other issues.
