### ISSUE TITLE
Change User Password does not show failure

### ISSUE THREAD

**Issue by Pakobbix** [realvnc-labs/rport#1070]
**Describe the bug**

When changing a password, via Settings -> Users or Profile settings, the UI shows password was updated. But when logging in again, it's still the old password.

the logs shows it's due to password minimal strength. But the frontend doesn't show it.

- Create new User.
- set password on creation (password12345)
- login with the new user, change it to another password (password54321)
- logout
- clear cookies
- login again
- get invalid authentication
- use old password and be logged in

So the User doesn't know if the password changes worked, until he repeating step 3 to 6 until step 7 is a success. Or monitoring the logs.

**Environment**
* RPort version:
   * Rport backend version 9.12
   * Rport frontend version 9.12.4 build 1132

* OS details (Linux distribution, and version or Windows version)
  * Ubuntu 22.04 Server

* Is rportd running inside a docker container?
  * no

* Are you using a reverse proxy? If yes, which one?
  * no

**Log file**

```
2023/05/25 11:38:46 debug: api-listener: error-response: payload: {Errors:[{Code: Title:Your password is too short Detail:password must be at least 14 characters}]}
2023/05/25 11:38:46.508 PUT /api/v1/users/testuser 400 1ms 116B (PrivateIP)
2023/05/25 11:38:46.566 GET /api/v1/user-groups 200 656µs 134B (PrivateIP)
2023/05/25 11:38:46.566 GET /api/v1/users 200 978µs 168B (PrivateIP)
```
**Screenshots**

![Screenshot 2023-05-25 135327](https://github.com/realvnc-labs/rport/assets/6762686/3eb1db09-c31e-426e-a343-94b571cf4c37)

**Additional context**

**Comment by thorstenkramm** [comment]
@Pakobbix Thanks for reporting. That's a great contribution. The bug is hereby confirmed. We are working on a fix.

**Comment by thorstenkramm** [comment]
🙇 Apologies for having released such a buggy version of the RPort UI.
Try updating the frontend to the latest version [frontend 0.9.12-5](https://download.rport.io/frontend/stable/) or newer, which contains a fix for this issue.


```
curl -L https://download.rport.io/frontend/stable/latest.php -o /tmp/rport-frontend-latest.zip
sudo -u rport sh -c "cd /var/lib/rport/docroot; unzip -o /tmp/rport-frontend-latest.zip"
rm /tmp/rport-frontend-latest.zip
cat /var/lib/rport/docroot/version.txt
```
 
Hard reload (Shift-Reload) your browser. _No need to restart the rport server._

🙏 Much appreciated if you confirm your issue has been solved by the update.

**Comment by thorstenkramm** [comment]
@Pakobbix You mean if "New Password" and "Confirm new password" don't match, you can submit the request? The "save" button is not disabled?

<img width="1054" alt="image" src="https://github.com/realvnc-labs/rport/assets/16852023/020ff397-160d-4e7e-8d27-af17e335dd29">

**Comment by thorstenkramm** [comment]
@Pakobbix 
And you don't get the same message you get in the logs on the UI?
<img width="1066" alt="image" src="https://github.com/realvnc-labs/rport/assets/16852023/3c104c32-d541-4f92-acdb-54f29960d93d">

I admit the position of the message is not ideal. It will be near the password input soon.

**Comment by Pakobbix** [comment]
Ah no, in the profile settings itself's it working like it should.

I was using the users tab.

I currently try to convince my CTO and Head of department to use rport for remote (patch) management and we usually create one time pass for first login. So I created the user for my colleagues, and tried to change it there for them to login.

The error i meant was at the users tab, where you also can add new users.  And there seems to be missing a check for the frontend that just always shows that you can do whatever you want it get's saved.

The error with the passwords that doesn't match but get saved in the backend, was also at the users management tab in the settings.

Sry that I didn't clarified that I was meaning the users tab and not the profile tab.
