### ISSUE TITLE
rPort 0.9.12 | Users other than default admin not authorized for basic auth usage

### ISSUE THREAD

**Issue by kylebial0** [realvnc-labs/rport#1073]
**Updated to include additional details 05/26/23**

**Describe the bug**
We generate an API token to make API calls to the rPort server to run scripts and check the audit log to confirm responses.

Previously in rPort 0.9.5, we were able to generate the API tokens per user, and the username of the admin who created the token would be the username for basic auth; If the admin user who generated the token was **Admin1** the basic auth would be: **Admin1:GENERATED_API_TOKEN_BY_Admin1**

 In rPort 0.9.12, it appears the API tokens have the ability to be viewed by all admin users. If we create an API token using the user account **Admin1** we still need to use the default admin account **admin** created at the time of installing rPort to be authorized to make the API call. If the default admin username is not used, the API call receives an unauthorized response.

**Comment by thorstenkramm** [comment]
@kylebial0 Sorry, I don't get it. What do you mean by "Once the username for basic auth is set to the default admin username"?

**Comment by kylebial0** [comment]
> @kylebial0 Sorry, I don't get it. What do you mean by "Once the username for basic auth is set to the default admin username"?

I have added additional details to help better explain the issue at hand. Please let me know if you need further information!

**Comment by thorstenkramm** [comment]
> it appears the API tokens have the ability to be viewed by all admin users.

No. That's not the case. API tokens are stored as hashes. Nobody can see them. 

What exactly is failing? The creation of the token or using the token?

> we still need to use the default admin account admin created at the time of installing rPort

Do you mean, even if you have created a token for the user `Admin1` you can only use this token for API requests if you use the username `admin`?  That would mean a user can use a foreign token. 

The conclusion of the above would be the username given for the API requests must always be `admin`?

What do you get if you call the API endpoint `/me`? Which username do you get? 

BTW. I cannot reproduce what you describe. I must always use the username the API token belongs to.

After creating a new token, check to whom it belongs in the database.
```
sqlite3 -table /var/lib/rport/api_token.db "select * from api_tokens"
```

**Comment by kylebial0** [comment]
I am finding I am no longer able to reproduce this issue. When I "discovered" this bug, I may have accidently logged in with the same user twice, but I am unsure.

I see you are 100% correct, the API tokens are not passed along to multiple users, indicating likely this was a careless mistake.

Thank you for the support!
