### ISSUE TITLE
Cannot manage client selection list in Schedule

### ISSUE THREAD

**Issue by edmen456** [realvnc-labs/rport#1076]
**Describe the bug**
Cannot manage the client selection list in the schedule tab. I expect that i can modify / add / remove the client group in the supervise schedule tab, but nothing shows up

![Untitled](https://github.com/realvnc-labs/rport/assets/23302844/9d3c2cb1-da79-4b06-8be6-0552cc644dd8)

Describe the environment where the bug occurs:

RPort version: 0.9.12
RPortfrontend: 0.9.12-2-build-1130
OS details: Ubuntu 22.04.2 LTS

**Comment by thorstenkramm** [comment]
@edmen456 A fix is underway.

**Comment by thorstenkramm** [comment]
This issue has been solved.

Try updating the frontend to the latest version [frontend 0.9.12-8](https://download.rport.io/frontend/stable/) or newer, which contains a fix for this issue.


```
curl -L https://download.rport.io/frontend/stable/latest.php -o /tmp/rport-frontend-latest.zip
sudo -u rport sh -c "cd /var/lib/rport/docroot; unzip -o /tmp/rport-frontend-latest.zip"
rm /tmp/rport-frontend-latest.zip
cat /var/lib/rport/docroot/version.txt
```
 
Hard reload (Shift-Reload) your browser. _No need to restart the rport server._

🙏 Much appreciated if you confirm your issue has been solved by the update.

**Comment by edmen456** [comment]
Thank you i confirm the problem is solved!
