### ISSUE TITLE
Users (including Admin) cannot change their own password

### ISSUE THREAD

**Issue by MarcSamD** [realvnc-labs/rport#1077]
**Describe the bug**
Going to the Profile page and checking the "Change password" box will display the old and new password fields, but there is just no "save" button to confirm the change...

**Environment**
rport-frontend-0.9.12-4-build-1132

**Comment by thorstenkramm** [comment]
@MarcSamD 
🙇 Apologies for having released such a buggy version of the RPort UI.
Try updating the frontend to the latest version [frontend 0.9.12-5](https://download.rport.io/frontend/stable/) or newer, which contains a fix for this issue.


```
curl -L https://download.rport.io/frontend/stable/latest.php -o /tmp/rport-frontend-latest.zip
sudo -u rport sh -c "cd /var/lib/rport/docroot; unzip -o /tmp/rport-frontend-latest.zip"
rm /tmp/rport-frontend-latest.zip
cat /var/lib/rport/docroot/version.txt
```
 
Hard reload (Shift-Reload) your browser. _No need to restart the rport server._

🙏 Much appreciated if you confirm your issue has been solved by the update.

**Comment by MarcSamD** [comment]
I confirm that the version rport-frontend-0.9.12-5-build-1133 solve this issue **but** it also re-open the issue of the inventory page having no scrollbar anymore...
