### ISSUE TITLE
Unable to create new user group

### ISSUE THREAD

**Issue by d3al** [realvnc-labs/rport#1081]
**Describe the bug**
Unable to create new user group. No add group button displayed in the "user group" screen. 
Unable to type in the groups field as it's a dropdown in the user add screen.
I can only select and type in a new group for my own account which is admin.

* RPort version: 9.12-5

**Comment by thorstenkramm** [comment]
@d3al New user groups are created from the user management.

https://github.com/realvnc-labs/rport/assets/16852023/49b1e98b-f1c8-4f27-a659-3f818beee961

Adding a new group while creating a new user is currently not supported. You must create the user first, either with no groups or only with existing groups. Once the user is created, you can add a new group.

I admit, it's not ideal, and we will improve that. But it's not a bug.

**Comment by d3al** [comment]
I understand. I messed with it and requires back and forth to get the group created but it does work.
