### ISSUE TITLE
Edit context menu item shown but not clickable

### ISSUE THREAD

**Issue by d3al** [realvnc-labs/rport#1082]
**Describe the bug**
Edit context menu item shown but not clickable in the Users screen except for the admin user object. I can't edit other users, only administrator.

Client_groups screen. Unable to click edit on all client groups expect one.

User_groups screen. Unable to click on edit except one object.

Seems like a permissions related problem but I'm logged in as admin account. **_All objects that I can click edit on are the first object in the datatable._**

* RPort version: 9.12-5

**Comment by thorstenkramm** [comment]
@d3al Bug confirmed. A fix is underway.

**Comment by thorstenkramm** [comment]
This issue has been solved.

Try updating the frontend to the latest version [frontend 0.9.12-8](https://download.rport.io/frontend/stable/) or newer, which contains a fix for this issue.


```
curl -L https://download.rport.io/frontend/stable/latest.php -o /tmp/rport-frontend-latest.zip
sudo -u rport sh -c "cd /var/lib/rport/docroot; unzip -o /tmp/rport-frontend-latest.zip"
rm /tmp/rport-frontend-latest.zip
cat /var/lib/rport/docroot/version.txt
```
 
Hard reload (Shift-Reload) your browser. _No need to restart the rport server._

🙏 Much appreciated if you confirm your issue has been solved by the update.

**Comment by d3al** [comment]
Confirmed, resolved. Thank you!
