### ISSUE TITLE
Loading Client list in GUI

### ISSUE THREAD

**Issue by petarkalafatic** [realvnc-labs/rport#1085]
Hello,

I created a group that has 25+ clients attached. When I click on the group it does not load all the clients in the group, just a portion of them. The `Load more` button loads another batch of clients but it does not leave the previous ones. It shows only the new ones. Another click on the `Load more` button shows me `No results found` and I cannot go back to the previous ones. The solution is to Refresh the tab and go all over again.

Can this be done so that by clicking on the client group, all the clients are listed? 
Here are some images in order of clicking:
![1](https://github.com/realvnc-labs/rport/assets/77074943/e83a5966-83e1-45e4-9b4d-75a2426b4990)

![2](https://github.com/realvnc-labs/rport/assets/77074943/1ecfd007-a363-485e-b3ef-23524b864611)

![3](https://github.com/realvnc-labs/rport/assets/77074943/6aae7533-d10e-46c7-b145-a81fdae5d3f9)

Also, could this border (in red) be more dynamic so the whole client name can be shown:

![5](https://github.com/realvnc-labs/rport/assets/77074943/f32ab3b0-84c5-4bac-8896-e65f6d46e84a)

Thank you

**Comment by thorstenkramm** [comment]
@petarkalafatic Thanks for reporting. You are right. The current implementation is ideal. Buttons to go forth and back are required. We will add them in a timely fashion.

**Comment by thorstenkramm** [comment]
This issue has been solved. We added the option to go forth and back.

Try updating the frontend to the latest version [frontend 0.9.12-9](https://download.rport.io/frontend/stable/) or newer, which contains a fix for this issue.


```
curl -L https://download.rport.io/frontend/stable/latest.php -o /tmp/rport-frontend-latest.zip
sudo -u rport sh -c "cd /var/lib/rport/docroot; unzip -o /tmp/rport-frontend-latest.zip"
rm /tmp/rport-frontend-latest.zip
cat /var/lib/rport/docroot/version.txt
```
 
Hard reload (Shift-Reload) your browser. _No need to restart the rport server._

🙏 Much appreciated if you confirm your issue has been solved by the update.
