### ISSUE TITLE
Message in Rport after each tab refresh

### ISSUE THREAD

**Issue by petarkalafatic** [realvnc-labs/rport#1087]
Hello @thorstenkramm :)

![Screenshot from 2023-06-01 09-10-55](https://github.com/realvnc-labs/rport/assets/77074943/a94773c8-1110-40d5-9fd7-b23a1b3bd9c1)

This appears for a second and disappears each time I refresh the Rport tab.

**Comment by thorstenkramm** [comment]
This issue has been solved.

Try updating the frontend to the latest version [frontend 0.9.12-8](https://download.rport.io/frontend/stable/) or newer, which contains a fix for this issue.


```
curl -L https://download.rport.io/frontend/stable/latest.php -o /tmp/rport-frontend-latest.zip
sudo -u rport sh -c "cd /var/lib/rport/docroot; unzip -o /tmp/rport-frontend-latest.zip"
rm /tmp/rport-frontend-latest.zip
cat /var/lib/rport/docroot/version.txt
```
 
Hard reload (Shift-Reload) your browser. _No need to restart the rport server._

🙏 Much appreciated if you confirm your issue has been solved by the update.
