### ISSUE TITLE
Failed to send request: EOF while creating Tunnel 

### ISSUE THREAD

**Issue by eksalih** [realvnc-labs/rport#1105]
when creating tunnel am geting bellow error only for one Client all other client working fine 

and when i do Journelcttl this error msg was there `2023/06/06 12:29:47 http: TLS handshake error from 217.165.248.91:38900: EOF

this server is not behind any proxy the server directly exposed to internet 

`Image attached here 
![image](https://github.com/realvnc-labs/rport/assets/69579940/4a7cccdc-abd5-45ae-9ea7-860768728c46)

**Comment by thorstenkramm** [comment]
@eksalih Is the log message from the server of the client? Please check both.
Can you execute commands and scripts on that client via rport?

**Comment by eksalih** [comment]
@thorstenkramm yes, the above log msg from server, I noted that the Client getting Disconnected and Connected and am not able to execute Script/commands from server to this client 
here is the logs from Client 

2023/06/07 09:14:59 info: client: connection wait stopped
2023/06/07 09:14:59 error: client: Could not send save_measurement: write tcp 172.16.1.148:51086->**server_ip**:8080: use of closed network connection
2023/06/07 09:14:59 info: client: Disconnected
2023/06/07 09:14:59 info: client: Trying to connect to ws://**domainname**:8080 ...
2023/06/07 09:14:59 info: client: Will wait up to 300.00 seconds for the server to respond
2023/06/07 09:14:59 error: client: Monitoring ended by context.Done
2023/06/07 09:14:59 info: client: Server's full fingerprint **Fingerprint_ID**
2023/06/07 09:15:04 info: client: Sending connection request.
2023/06/07 09:15:04 info: client: Connected to server_ip:8080 within 412.808053ms
2023/06/07 09:15:47 info: client: connection wait stopped
2023/06/07 09:15:47 error: client: Monitoring ended by context.Done
2023/06/07 09:15:47 info: client: Disconnected
2023/06/07 09:15:47 error: client: connection error: websocket: close 1006 (abnormal closure): unexpected EOF
2023/06/07 09:15:47 info: client: Retrying in 5.000000008s...
2023/06/07 09:15:52 info: client: Trying to connect to ws://**domainname**:8080 ...
2023/06/07 09:15:52 info: client: Will wait up to 300.00 seconds for the server to respond
2023/06/07 09:15:52 info: client: Server's full fingerprint **server_fingerprint_id**
2023/06/07 09:15:59 info: client: Sending connection request.
2023/06/07 09:15:59 info: client: Connected to **server_ip**:8080 within 42.129243ms
2023/06/07 09:19:36 error: client: Failed to send keepalive (client to server ping): conn.SendRequest(ping), timeout 30s exceeded
2023/06/07 09:19:36 info: client: connection wait stopped
2023/06/07 09:19:36 info: client: Disconnected
2023/06/07 09:19:36 info: client: Trying to connect to ws://**domainname**:8080 ...
2023/06/07 09:19:36 info: client: Will wait up to 300.00 seconds for the server to respond
2023/06/07 09:19:36 error: client: Monitoring ended by context.Done
2023/06/07 09:19:36 info: client: Server's full fingerprint **server_fingerprinf_id**
2023/06/07 09:19:46 info: client: Sending connection request.
2023/06/07 09:19:46 info: client: Connected to **server_ip**:8080 within 52.164436ms

**Comment by thorstenkramm** [comment]
@eksalih This looks like a firewall or connectivity issue. Please check your local and network firewalls. You need unfiltered outgoing connections over port 8080.

**Comment by eksalih** [comment]
@thorstenkramm okey, i suspect the same let me reach out the firewall team as this managed by Telephone service Provider. 

will let you know the result after checking this

**Comment by eksalih** [comment]
@thorstenkramm  am closing this ticket as per Firewall team all traffic going out is open, i believe there is some rule which are blocking the connection even I tried on port 80 but got same result.

i dont have access to the firewall to check the rulez coz this firewall managed by the service provider team
