### ISSUE TITLE
Stored tunnel list limited to 10 Entries in rportd 0.9.12 / rport-frontend-0.9.12-7-build-1135 

### ISSUE THREAD

**Issue by trafagdim** [realvnc-labs/rport#1114]
The entries in stored tunnels shows max 10 entries. There ist also no pagination shown and there ist no menupoint to edit the entry.
![grafik](https://github.com/realvnc-labs/rport/assets/129991131/deb0ecc4-cb62-4a89-9830-82a0dc28a58e)

RPortd 0.9.12
Frontdend 0.9.12-7-build-1135

**Comment by trafagdim** [comment]
The issue still exists in rport-frontend-0.9.12-12-build-1140.  
If there are stored more than 10 tunnels on one host only the first 10 are displayed in the UI.

**Comment by thorstenkramm** [comment]
@trafagdim Thanks for reporting. You are right. The default page size of 10 applies. A fix is underway. We will increase the limit to 100.

**Comment by thorstenkramm** [comment]
@trafagdim Please update your frontend to rport-frontend-0.9.12-13-build-1141.zip. This solves the issue.
