### ISSUE TITLE
The last groups are not visible

### ISSUE THREAD

**Issue by petarkalafatic** [realvnc-labs/rport#1118]
Hello @thorstenkramm :) 

![Screenshot from 2023-06-14 15-03-31](https://github.com/realvnc-labs/rport/assets/77074943/968b2b81-2702-41cb-8e1b-6cd8b9e58dc5)

As you can see in the screenshot above. The Next button goes gray but there are still some groups to be loaded and I cannot load them. 

Thank you

**Comment by thorstenkramm** [comment]
This issue has been solved.

Try updating the frontend to the latest version [frontend 0.9.12-11](https://download.rport.io/frontend/stable/) or newer, which contains a fix for this issue.


```
curl -L https://download.rport.io/frontend/stable/latest.php -o /tmp/rport-frontend-latest.zip
sudo -u rport sh -c "cd /var/lib/rport/docroot; unzip -o /tmp/rport-frontend-latest.zip"
rm /tmp/rport-frontend-latest.zip
cat /var/lib/rport/docroot/version.txt
```
 
Hard reload (Shift-Reload) your browser. _No need to restart the rport server._

🙏 Much appreciated if you confirm your issue has been solved by the update.

**Comment by petarkalafatic** [comment]
The issue is still there. The frontend update did not work.
