### ISSUE TITLE
Cannot load all clients in a group

### ISSUE THREAD

**Issue by petarkalafatic** [realvnc-labs/rport#1120]
The group I created loads only 20 clients but has 27. I cannot see the rest in the GUI. The "Next" button is grey.

**Comment by thorstenkramm** [comment]
Are you running the latest version of the frontend.

Try updating the frontend to the latest version [frontend 0.9.12-11](https://download.rport.io/frontend/stable/) or newer, which contains a fix for this issue.


```
curl -L https://download.rport.io/frontend/stable/latest.php -o /tmp/rport-frontend-latest.zip
sudo -u rport sh -c "cd /var/lib/rport/docroot; unzip -o /tmp/rport-frontend-latest.zip"
rm /tmp/rport-frontend-latest.zip
cat /var/lib/rport/docroot/version.txt
```
 
Hard reload (Shift-Reload) your browser. _No need to restart the rport server._

🙏 Much appreciated if you confirm your issue has been solved by the update.

**Comment by petarkalafatic** [comment]
the version I use:    ` rport-frontend-0.9.12-11-build-1139 `

**Comment by eksalih** [comment]
@thorstenkramm am using the latest frontend and am facing the same Issue

**Comment by thorstenkramm** [comment]
@eksalih @petarkalafatic Maybe I don't get it right. Can you post of screenshot of the section where only 20 clients are displayed, but you expect more?

**Comment by petarkalafatic** [comment]
![Screenshot from 2023-06-16 14-56-08](https://github.com/realvnc-labs/rport/assets/77074943/e0a16094-a52f-4bc4-8d56-f4cee5affc5c)

The next button option should me able to load additional clients of the group.

**Comment by eksalih** [comment]
![20230616_170612](https://github.com/realvnc-labs/rport/assets/69579940/88326af5-d469-4ed3-bee8-75d7665bddce)
Unable to click next button

**Comment by thorstenkramm** [comment]
@eksalih @petarkalafatic Finally I could reproduce it. A fix is underway.

**Comment by thorstenkramm** [comment]
@eksalih @petarkalafatic Try rport-frontend-0.9.12-12-build-1140.zip. I think we solved the issue.

**Comment by eksalih** [comment]
@thorstenkramm yes this is fixed
