### ISSUE TITLE
root access to machines doesn't work after migration to a new server

### ISSUE THREAD

**Issue by cilku** [realvnc-labs/rport#1125]
I've setup a new server and moved all my machines to the new one. By unsintalling rport client on each machine and reinstalling and pairing the new one. 

I saw that I couldn't add labels to my machines, it was because the file "/var/lib/rport/client_attributes.json" was owned by root:root, quick fix was: "chown rport:root /var/lib/rport/client_attributes.json". It worked! Now I wanted to rollout this change to all machines via rPort, but I couldn't (see screenshot):

Tried it with a few other commands like apt-get, or cat some root files, same result. To me it looks like the rport client doesn't have root access anymore. 

Bug is related to `rport` (client)

**Environment**
* RPort version_ 0.9.12
* OS details: Ubuntu 22.04.2 LTS
* no Docker environment
* no Reverse Proxy 

**Log file**
Before submitting a bug report, inspect the log files of client and server.
`/var/log/rport/rportd.log` for the server and `/var/log/rport/rport.log` or `C:\Program Files\rport\rport.log` for the client.
[Increase the log level to debug](https://github.com/realvnc-labs/rport/blob/0.9.0/rport.example.conf#L169-L171) and try to reproduce the error.
Include relevant lines into your report.

**Screenshots**
![image](https://github.com/realvnc-labs/rport/assets/58217188/8f730b93-3016-4cf9-b63a-c74e58ce01c3)

**Additional context**

**Comment by thorstenkramm** [comment]
@cilku On installing the client did you execute the installer with the following parameters?
`rport-installer.sh -x -s -r -b -i` 
`-s` creates the sudo rules needed to execute scripts with root rights.
Look at `/etc/suoders.d/`, do you have rport sudo rules there?

If file(s) are missing, create `/etc/sudoers.d/rport-all-cmd` with this content:
```
rport ALL=(ALL) NOPASSWD:ALL
```

**Comment by cilku** [comment]
@thorstenkramm,

yes: always with rport-installer.sh -x -s -r -b -i
also
yes, sudoers.d looks all right. 
![image](https://github.com/realvnc-labs/rport/assets/58217188/0073589f-186c-4d3f-b746-ad0fdffe324e)

Sorry I should have mentioned that I've already checked that. Because it was my first thought too.

Non root commands run on every machine:
![image](https://github.com/realvnc-labs/rport/assets/58217188/8ca487c7-bf2e-450a-b6d3-ec72e211ae64)

**Comment by thorstenkramm** [comment]
@cilku Is the issue related to the concurrent script execution only? Can you execute a script with sudo from a single client?

**Comment by thorstenkramm** [comment]
@cilku On your screenshot, all lights are green. What messages are there if you unfold the script response?

**Comment by thorstenkramm** [comment]
@cilku The apt-get error is expected because you didn't use sudo. The "Use sudo" toggle is disabled. Please enable and try again.
