### ISSUE TITLE
Resetting 2FA for specific user in the redesigned UI

### ISSUE THREAD

**Issue by qraleq** [realvnc-labs/rport#1128]
I cannot find a way to reset 2FA for a user in the redesigned dashboard. Is the feature missing or changed somehow compared to how it was implemented before?

Thank you!

**Comment by thorstenkramm** [comment]
@qraleq Are you referring to email-based 2FA or TOTP?
From the user management, you can change the email for 2FA.
For TOTP there is no option to reset apart from using SQL directly on the database. And this didn't change with the new dashboard because the API doesn't support a reset of the TOTP secret.

**Comment by thorstenkramm** [comment]
@qraleq You are right. The reset button is missing. We are on it.

**Comment by qraleq** [comment]
Perfect! Thank you

**Comment by thorstenkramm** [comment]
This issue has been solved.

Try updating the frontend to the latest version [frontend 0.9.12-14](https://download.rport.io/frontend/stable/) or newer, which contains a fix for this issue.


```
curl -L https://download.rport.io/frontend/stable/latest.php -o /tmp/rport-frontend-latest.zip
sudo -u rport sh -c "cd /var/lib/rport/docroot; unzip -o /tmp/rport-frontend-latest.zip"
rm /tmp/rport-frontend-latest.zip
cat /var/lib/rport/docroot/version.txt
```
 
Hard reload (Shift-Reload) your browser. _No need to restart the rport server._

🙏 Much appreciated if you confirm your issue has been solved by the update.

**Comment by qraleq** [comment]
Confirming that I see the button... but it would be great to give some feedback such as "TOTP successfully reset" when action is successful.

Thank you!

**Comment by thorstenkramm** [comment]
@qraleq Try [this update](https://download.rport.io/frontend/stable/rport-frontend-0.9.12-15-build-1143.zip). It returns a confirmation on pressing the reset button.
