### ISSUE TITLE
Safari tunnel button problem

### ISSUE THREAD

**Issue by SuperKali** [realvnc-labs/rport#1133]
Hello again,

on safari I can't manage the active tunnel, I tried with microsoft edge and it works, maybe is something about the padding of the button.

I attach the video: https://tempclip.com/en/c4Hm0LFEXeft4pm/watch

Regards.

**Comment by thorstenkramm** [comment]
This issue has been solved.

Try updating the frontend to the latest version [frontend 0.9.12-14](https://download.rport.io/frontend/stable/) or newer, which contains a fix for this issue.


```
curl -L https://download.rport.io/frontend/stable/latest.php -o /tmp/rport-frontend-latest.zip
sudo -u rport sh -c "cd /var/lib/rport/docroot; unzip -o /tmp/rport-frontend-latest.zip"
rm /tmp/rport-frontend-latest.zip
cat /var/lib/rport/docroot/version.txt
```
 
Hard reload (Shift-Reload) your browser. _No need to restart the rport server._

🙏 Much appreciated if you confirm your issue has been solved by the update.

**Comment by SuperKali** [comment]
Hello @thorstenkramm,

There's something that not working properly:

<img width="1800" alt="image" src="https://github.com/realvnc-labs/rport/assets/19473898/c03909e5-6e4f-4d59-b502-ba90a9e4d9f7">

Can you check?

Regards

**Comment by thorstenkramm** [comment]
@SuperKali Try [this update](https://download.rport.io/frontend/stable/rport-frontend-0.9.12-15-build-1143.zip)

**Comment by SuperKali** [comment]
@thorstenkramm on other browser seems fixed, I will try later in safari.

**Comment by SuperKali** [comment]
@thorstenkramm it's normal, the gray on the right?

![image](https://github.com/realvnc-labs/rport/assets/19473898/301afec8-54e8-422c-8cda-dc24a88f5904)

**Comment by thorstenkramm** [comment]
@SuperKali Yes. This colour gradient is currently correct. It's part of the table template. Somewhere in the near future, we will unify all tables and the gradient will disappear.
