### ISSUE TITLE
Mobile browsing problem

### ISSUE THREAD

**Issue by SuperKali** [realvnc-labs/rport#1137]
Hello,

I experiencing a problem when I browsing the panel from my iPhone.

https://share.icloud.com/photos/005f7gQCY5glsxGlsGT-xaf7A

It’s possible a fix?

regards.

**Comment by thorstenkramm** [comment]
We are aware of the poor performance on mobile devices.
Hence, we are working on a mobile optimized version to be released mid of July 2023.
I'll close the issue because it's duplicated.
