### ISSUE TITLE
Tags cannot be edited from user interface

### ISSUE THREAD

**Issue by t347s** [realvnc-labs/rport#1138]
**Describe the bug**
Tags cannot be edited from user interface, when i try to modify the error appear:
![image](https://github.com/realvnc-labs/rport/assets/31503790/8ce86d49-b3c1-4a1b-b4ee-cf9ada454d02)

**Environment**
Describe the environment where the bug occurs:

* RPort version: server 0.9.12; rport-frontend-0.9.12-13-build-1141
* OS details (Linux distribution, and version or Windows version): Ubuntu 20.04
* Is rportd running inside a docker container?: No
* Are you using a reverse proxy? If yes, which one?: No

Now i have to edit manually the file /var/lib/rport/client_attributes.json not rport.conf on every client.

Thank you

**Comment by thorstenkramm** [comment]
@t347s This is not an error of the user interface. It's an error raised by the client. 
Please check the file mode and owner of `client_attributes.json` on the client.

**Comment by t347s** [comment]
It's root the owner, so if i give the permissions to the rport user should work? This permision will not create other problems?

Thanks!

**Comment by thorstenkramm** [comment]
@t347s Correct. The file shall be owned by the rport user. This doesn't create problems.
