### ISSUE TITLE
Client cannot be deleted from Inventory page

### ISSUE THREAD

**Issue by t347s** [realvnc-labs/rport#1139]
**Describe the bug**
Client does not get deleted from inventory page after click on button: "Delete from Inventory" nothing happends:
![image](https://github.com/realvnc-labs/rport/assets/31503790/9d830fb7-4bc8-4cbd-a751-5299fd65583b)

**Environment**
Describe the environment where the bug occurs:

* RPort version: server 0.9.12; rport-frontend-0.9.12-13-build-1141
* OS details (Linux distribution, and version or Windows version): Ubuntu 20.04
* Is rportd running inside a docker container?: No
* Are you using a reverse proxy? If yes, which one?: No

Thank you!

**Comment by thorstenkramm** [comment]
@t347s Thanks for reporting. I can confirm the bug. The button is without function. 
In the meantime, look for the client on the client list and delete from there. This button is working.

**Comment by t347s** [comment]
Yes, i can confirm, from there you can delete it, i forgot to mention, sorry...
