### ISSUE TITLE
Unable to install client on RHCOS 4.12.17

### ISSUE THREAD

**Issue by t347s** [realvnc-labs/rport#1140]
**Describe the bug**
Hi,

I am trying to install client on a RHCOS operating system and i receive the following error:
```
sudo sh rport-installer.sh -x -s -r -b -i -l
Installing rport client
Detected Linux Distribution: Red Hat Enterprise Linux CoreOS 411.86.202306021408-0 (Ootpa)
Success: http://xxxx.xxxxxx.xxxxx:8000 is reachable. All good.
[*] RPort will use RPM package ...
error: can't create transaction lock on /usr/share/rpm/.rpm.lock (Read-only file system)
error: https://repo.rport.io/key.gpg: key 1 import failed.

An error occurred.
Try running in debug mode with 'sh -x rport-installer.sh -x -s -r -b -i -l'
Ask for help on https://github.com/realvnc-labs/rport-pairing/discussions/categories/help-needed
```
In case you know it. Is the bug related to `rportd` (server) or `rport` (client)?
I realy don't know, on the previous version of rport server (0.9.5) the install run ok, some problems with selinux but it worked.

**Environment**
Describe the environment where the bug occurs:

* RPort version: server 0.9.12; rport-frontend-0.9.12-13-build-1141
* OS details (Linux distribution, and version or Windows version): Ubuntu 20.04
* Is rportd running inside a docker container?: No
* Are you using a reverse proxy? If yes, which one?: No

L.E. The enviroment with RHCOS i was forced to rebuild, so i tried to reinstall client.

Thank you!

**Comment by thorstenkramm** [comment]
@t347s The error is pretty clear.

> `error: can't create transaction lock on /usr/share/rpm/.rpm.lock (Read-only file system)`

It's not related to rport.  
RHCOS prevents the manipulation of the package database because it uses a pre-defined image. 
Maybe [this article](https://access.redhat.com/documentation/de-de/openshift_container_platform/4.13/html/post-installation_configuration/coreos-layering) helps. 

As a last measure, you can skip using RPMs and download the binaries manually.

**Comment by t347s** [comment]
Hi,
Yes, it is possible that the problem is on the OS side, i used the first time (when the install of the rport client worked) version 4.12.0 of the os; it is possible that somewhere on the path to 4.12.17 RHEL made some changes.

The conclusion is that installation of rport client on RHCOS is no longer possible.

Thank you!

**Comment by thorstenkramm** [comment]
@t347s 
I wouldn't say it's not possible. I'm quite sure it is. But due to the special requirements of this OS the default script is not suitable. By using the binaries and not the RPMs you will probably get it worling.
