### ISSUE TITLE
Unable to create 2FA after first login

### ISSUE THREAD

**Issue by rbr-acs** [realvnc-labs/rport#1143]
**Describe the bug**
After the first login, the user can`t create the 2FA because the is no QR Code after the login.

**Environment**
Describe the environment where the bug occurs:

* RPort version 0.9.12
* Debian 11
* no Docker
* Used with HAProxy

**Comment by thorstenkramm** [comment]
@rbr-acs Can you please paste a screenshot of what is shown instead of the QR code?
