### ISSUE TITLE
Error when editing user group - json: unknown field "commands_restricted"

### ISSUE THREAD

**Issue by qraleq** [realvnc-labs/rport#1148]
I'm getting this error when editing permissions for a user group:
```
json: unknown field "commands_restricted"
```
It pops up regardless of the options I choose here:

![image](https://github.com/realvnc-labs/rport/assets/13619177/a9f4373f-9291-4ebc-8f14-dfc8c297afdf)

Thank you!

**Comment by thorstenkramm** [comment]
@qraleq 

This issue has been solved.

Try updating the frontend to the latest version [frontend 0.9.12-16](https://download.rport.io/frontend/stable/) or newer, which contains a fix for this issue.


```
curl -L https://download.rport.io/frontend/stable/latest.php -o /tmp/rport-frontend-latest.zip
sudo -u rport sh -c "cd /var/lib/rport/docroot; unzip -o /tmp/rport-frontend-latest.zip"
rm /tmp/rport-frontend-latest.zip
cat /var/lib/rport/docroot/version.txt
```
 
Hard reload (Shift-Reload) your browser. _No need to restart the rport server._

🙏 Much appreciated if you confirm your issue has been solved by the update.
