### ISSUE TITLE
Installing Windows client failed

### ISSUE THREAD

**Issue by Flachdachs** [realvnc-labs/rport#1155]
We are running a private paring server installation since the time as 0.9.5 was the current version. We didn't change anything since then and it usually works fine. Today we tried to install an rport client for Windows but it failed. After searching for the reason we found out that the download returns a file which is not the a valid zip archive. However downloading the file manually works fine. We could trick the installer with a file pre-downloaded as C:\Windows\temp\rport_stable_windows_x86_64.zip and then the install script run fine.

Details:
- The install script tries to download from `https://downloads.rport.io/rport/stable/latest.php?arch=windows_x86_64` and this returns whatever but not a zip archive.
- Opening `https://downloads.rport.io/rport/stable/` in a browser and downloading the last file in the list - which resolves to `https://github.com/realvnc-labs/rport/releases/download/0.9.12/rport_0.9.12_windows_x86_64.zip` - returns a valid zip archive.

**Comment by thorstenkramm** [comment]
@Flachdachs 
Meanwhile, we introduced MSI packages. The new link is `https://downloads.rport.io/rport/stable/latest.php?filter=windows_x86_64.zip`.
We also updated the pairing service to be compatible with the new download URLs. 
Updating the pairing service to the latest version will solve the issue.

**Comment by Flachdachs** [comment]
I understand, but why does the old link downloads garbage instead of either giving the zip file for compatibility reason or a proper error message?

**Comment by thorstenkramm** [comment]
If the filter is not precise enough, you get a redirect to the first possible download, which is now the MSI Package. 
You don't get garbage. The old script is not prepared for processing MSI files.
