### ISSUE TITLE
Browser RDP is greyed out on new installation of latest version why?

### ISSUE THREAD

**Issue by bribeck** [realvnc-labs/rport#1163]
I installed the newest version .9.12 but when I try to create an RDP tunnel the option for the browser is Greyed out, and I can't select it. I thought the newest version came with everything need to do this.

**Comment by thorstenkramm** [comment]
It depends on the OS. If the report server runs inside docker or on RPM-based distros, web based RDP is not supported out of the box. You need to install/compile guacamole manually from the sources.
For Debian and Ubuntu we have packaged the Guacamole dependencies, so you just need to [install our DEBs from here](https://github.com/realvnc-labs/rport-guacamole) and [activate Guacamole in the `rportd.conf`](https://github.com/realvnc-labs/rport/blob/0.9.12/rportd.example.conf#L220-L222).
