### ISSUE TITLE
Clicking on Library Results in Neverending Stream of Requests

### ISSUE THREAD

**Issue by shawnweeks** [realvnc-labs/rport#1183]
**Describe the bug**
Clicking on the Library tab of the RPort Server UI results in a never ending stream of rest api calls like `/api/v1/library/commands?sort=name&page[limit]=100&page[offset]=14700` that don't stop until you click on to another tab and refresh the browser window.

A feature request is not a bug. Feature requests are welcome. Follow [this link](https://github.com/realvnc-labs/rport/discussions/categories/roadmap-feature-wishes-ideas).

In case you know it. Is the bug related to `rportd` (server) or `rport` (client)?

**Environment**
Describe the environment where the bug occurs: Firefox latest on MacOS 13.x

* RPort version: 0.9.12
* OS details (Linux distribution, and version or Windows version): Debian Bookworm
* Is rportd running inside a docker container? No
* Are you using a reverse proxy? If yes, which one? HAProxy for UI Only

**Log file**
Before submitting a bug report, inspect the log files of client and server.
`/var/log/rport/rportd.log` for the server and `/var/log/rport/rport.log` or `C:\Program Files\rport\rport.log` for the client.
[Increase the log level to debug](https://github.com/realvnc-labs/rport/blob/0.9.0/rport.example.conf#L169-L171) and try to reproduce the error.
Include relevant lines into your report.
```
2023/08/10 13:41:33.236 GET /api/v1/library/commands 200 426µs 52B (10.10.22.20)
2023/08/10 13:41:33.264 GET /api/v1/library/commands 200 391µs 52B (10.10.22.20)
2023/08/10 13:41:33.288 GET /api/v1/library/commands 200 386µs 52B (10.10.22.20)
2023/08/10 13:41:33.408 GET /api/v1/library/commands 200 400µs 52B (10.10.22.20)
2023/08/10 13:41:33.437 GET /api/v1/library/commands 200 398µs 52B (10.10.22.20)
2023/08/10 13:41:33.463 GET /api/v1/library/commands 200 389µs 52B (10.10.22.20)
2023/08/10 13:41:33.488 GET /api/v1/library/commands 200 433µs 52B (10.10.22.20)
2023/08/10 13:41:33.514 GET /api/v1/library/commands 200 399µs 52B (10.10.22.20)
2023/08/10 13:41:33.538 GET /api/v1/library/commands 200 664µs 52B (10.10.22.20)
2023/08/10 13:41:33.566 GET /api/v1/library/commands 200 419µs 52B (10.10.22.20)
2023/08/10 13:41:33.594 GET /api/v1/library/commands 200 390µs 52B (10.10.22.20)
2023/08/10 13:41:33.622 GET /api/v1/library/commands 200 381µs 52B (10.10.22.20)
2023/08/10 13:41:33.652 GET /api/v1/library/commands 200 404µs 52B (10.10.22.20)
2023/08/10 13:41:33.688 GET /api/v1/library/commands 200 395µs 52B (10.10.22.20)
2023/08/10 13:41:33.716 GET /api/v1/library/commands 200 420µs 52B (10.10.22.20)
2023/08/10 13:41:33.753 GET /api/v1/library/commands 200 384µs 52B (10.10.22.20)
2023/08/10 13:41:33.786 GET /api/v1/library/commands 200 468µs 52B (10.10.22.20)
```

**Screenshots**

<img width="1903" alt="Screenshot 2023-08-10 at 8 41 52 AM" src="https://github.com/realvnc-labs/rport/assets/9768773/69c0b09e-3572-4df6-a312-2c90b972fdd1">

**Additional context**

**Comment by shawnweeks** [comment]
This only happens on an empty library, as soon as there is at least one item in `Command` and `Scripts` it behaves normally.

**Comment by thorstenkramm** [comment]
@shawnweeks 


This issue has been solved.

Try updating the frontend to the latest version [frontend 0.9.12-17](https://download.rport.io/frontend/stable/) or newer, which contains a fix for this issue.


```
curl -L https://download.rport.io/frontend/stable/latest.php -o /tmp/rport-frontend-latest.zip
sudo -u rport sh -c "cd /var/lib/rport/docroot; unzip -o /tmp/rport-frontend-latest.zip"
rm /tmp/rport-frontend-latest.zip
cat /var/lib/rport/docroot/version.txt
```
 
Hard reload (Shift-Reload) your browser. _No need to restart the rport server._

🙏 Much appreciated if you confirm your issue has been solved by the update.

**Comment by shawnweeks** [comment]
@thorstenkramm Confirmed that this fixes the issue. Instead of a never ending load I get a `No data found` message. Thanks for fixing it.
