### ISSUE TITLE
Cannot generate the API token

### ISSUE THREAD

**Issue by wakaka6** [realvnc-labs/rport#1230]
**Describe the bug**

Cannot generate the API token.

In case you know it. Is the bug related to `rportd` (server) or `rport` (client)? rportd

**Environment**
Describe the environment where the bug occurs:

* RPort version 0.9.12/rport-frontend-stable-0.8.0-build-1092
* OS details (Linux distribution, and version or Windows version) CentOS7
* Is rportd running inside a docker container? no

**Log file**
Before submitting a bug report, inspect the log files of client and server.
`/var/log/rport/rportd.log` for the server and `/var/log/rport/rport.log` or `C:\Program Files\rport\rport.log` for the client.
[Increase the log level to debug](https://github.com/realvnc-labs/rport/blob/0.9.0/rport.example.conf#L169-L171) and try to reproduce the error.
Include relevant lines into your report.
```
2023/09/11 18:40:26 debug: api-listener: error-response: payload: {Errors:[{Code: Title:use new token management on /me/tokens Detail:}]}
2023/09/11 18:40:26.931 POST /api/v1/me/token 410 1ms 100B (192.168.1.15)
```

**Screenshots**
When I follow the [tutorial](https://kb.rport.io/digging-deeper/using-the-api) to generate the api it prompts me with "use new token management on /me/tokens"
![image](https://github.com/realvnc-labs/rport/assets/48764488/82e0fe22-81b9-441c-8ebb-671b4cf266c7)
When I go to /me/tokens I get a 404.
![image](https://github.com/realvnc-labs/rport/assets/48764488/c11731ee-cf5e-494e-9977-2001a9a6fea8)

**Comment by thorstenkramm** [comment]
@wakaka6 You are using a frontend that's not compatible with your backend. The API tokens have changed. Only the new frontend can generate them. 

Try updating the frontend to the latest version [frontend 0.9.12-17](https://download.rport.io/frontend/stable/) or newer.


```
curl -L https://download.rport.io/frontend/stable/latest.php -o /tmp/rport-frontend-latest.zip
sudo -u rport sh -c "cd /var/lib/rport/docroot; unzip -o /tmp/rport-frontend-latest.zip"
rm /tmp/rport-frontend-latest.zip
cat /var/lib/rport/docroot/version.txt
```
 
Hard reload (Shift-Reload) your browser. _No need to restart the rport server._

🙏 Much appreciated if you confirm your issue has been solved by the update.

**Comment by wakaka6** [comment]
Everything was perfect. Thank you.
