### ISSUE TITLE
Client Handshake failed

### ISSUE THREAD

**Issue by mahafree** [realvnc-labs/rport#712]
I'm currently testing rport version 0.80
I have added 10+ clients without an issue. (everything works perfectly)

With one client I get the error "2022/10/04 11:44:44 client: ssh: handshake failed: websocket: unexpected reserved bits 0x40" in the client log file.
Tried reinstalling the client software multiple times and tried with different "Client access" codes.
Is this a known issue?

**Comment by thorstenkramm** [comment]
@mahafree This issue can be caused by a transparent HTTP proxy. Some firewalls pass all traffic through a proxy for virus scanning. Check this and if it's the case, create an exception to not pass traffic towards your rport server through the proxy.

**Comment by mahafree** [comment]
Thanks for the info!
I will check that.

**Comment by mahafree** [comment]
I've ended up installing rinetd as described [here](https://kb.rport.io/need-help/troubleshoot-common-problems/client-is-not-connecting).
Maybe it's helpful for somebody with the same issue.

**Comment by wangshiok** [comment]
thanks, 

> I've ended up installing rinetd as described [here](https://kb.rport.io/need-help/troubleshoot-common-problems/client-is-not-connecting). Maybe it's helpful for somebody with the same issue.

thanks, it certainly point me to right solution, by using 2nd port, it works much more smoother too, I was wondering some clients took so long to be online
