### ISSUE TITLE
Duplicate Client ID

### ISSUE THREAD

**Issue by bloesss** [realvnc-labs/rport#824]
Computer says "client ID is already connected" with another computer name.

I have a client with a PC "C4EN014" and "C4EN015" (and several other Computers that work).

C4EN014 now says:

Connection error: client is already connected: C4EN015 [03000200-0400-0500-0006-000700080009]

And I can see that C4EN015 indeed has exactly that ID.

I am using the same Credentials for all the Clients per Client Group.

**Comment by bloesss** [comment]
I found out that you can google my client ID "03000200-0400-0500-0006-000700080009":

https://forums.ivanti.com/s/question/0D54O00006T4a6ZSAR/computer-mit-identischen-smbios-guidwerten-gefunden?language=de

seems like there are computers with that uuid all over the world.
That could be a problem in the way rport generates the client ID from the uuid.

My Problem: There seem to be several Computers with that Problem.
Changing the client ID to something random helps, but I cannot change them all manually.

What format has it to be? How could a cmd batch that changes the Client ID to something random look like?

**Comment by thorstenkramm** [comment]
@bloesss Thanks for adding this useful information.
We take the UUID given by Windows. Seems this is not reliable.
Providing your own ID is supported. The id must be unique across your infrastructure. The ID can have any format.
You can use PowerShell [`New-Guid`](https://learn.microsoft.com/de-de/powershell/module/microsoft.powershell.utility/new-guid?view=powershell-7.3).
We will consider changing the default to this instead of relying on the Windows Smbios Guid.
Thanks again for your help.

**Comment by bloesss** [comment]
Glad to help optimizing this great project :)

I will give New-Guid a try. First need a way to filter the duplicate client IDs. Think this could be solved with zabbix and wmi

**Comment by bloesss** [comment]
I think it could be optimized as I am not a regex expert, but this powershell works for me:

`net stop rport
$newid = [guid]::NewGuid().ToString()
$file = 'C:\Program Files\rport\rport.conf'
$regex = '(?<=id = ")[^"]*'
(Get-Content $file) -replace $regex, $newid | Set-Content $file
net start rport`

**Comment by cryptodev4** [comment]
Hi, I'm using Rport in production envonriment, and I realized that in the installation momento the UUID is not been generated by rport-installer.sh (for Linux envonronment).

So when I tried to install a lot of IoT devices, I had to change the UUID manually in every device.

Maybe installer has a bug.

**Comment by thorstenkramm** [comment]
@cryptodev4 The installer doesn't have a bug. It takes the UUID given by the devices taken from `/etc/machine-id` or `/var/lib/dbus/machine-id`. These ids should be unique. If you can't make them unique, you can create your own id based on whatever criteria you like.

**Comment by tobias-scheepers** [comment]
Hi, it seems also for us the install script does in fact not take the id stored in `/etc/machine-id` also for us causing conflicting client-id's. When running the installer with the -d flag we even get a client id in rport named: `gen_uuid`

![Screenshot 2023-08-07 at 16-28-44 rport](https://github.com/realvnc-labs/rport/assets/78491258/d52d88cf-d059-43af-a40e-9d546adee2f7)

**Comment by thorstenkramm** [comment]
@tobias-scheepers You are right. The `-d` option to generate the UUID independently of the `/etc/machine-id` was broken.
It's fixed now. Generate a new pairing code and download the installer script again. With `-d` you will always get a unique ID for your systems even if the machine ID is duplicated.

**Comment by tobias-scheepers** [comment]
Thanks for the fast fix. Is rport by chance also overwriting `/etc/machine-id` at some point? We are currently deploying ubuntu machines and using cloud-init writing a uuid to `/etc/machine-id`. However once rport is installed and the system reboots a different value is added to the /etc/machine-id

In any case I will have a look to the latest installer script. Again thank you for the fast turn around

**Comment by thorstenkramm** [comment]
@tobias-scheepers RPort is not writing to `/etc/machine-id`.
The installer script is plain text. Just open with an editor and check yourself. 
I guess cloud-init is creating a new id on each boot.

**Comment by tobias-scheepers** [comment]
Thanks @thorstenkramm fro confirming. We found the problem somewhere else indeed. Once more thank you for the great product.
