### ISSUE TITLE
user auth mysql: wrong size of field token

### ISSUE THREAD

**Issue by kstieger** [realvnc-labs/rport#875]
**user auth mysql: wrong size of field token**
The bcrypted API token doesn't fit into a 
```
`token` char(36) DEFAULT NULL
```
 field as shown on https://oss.rport.io/get-started/api-authentication/#database

I changed it to
```
`token` char(128) DEFAULT NULL,
```
128 chars might be too much for a bcrypted token, but it works fine now for me.

This bug is related to rportd if user auth is stored in mysql

**Environment**
Describe the environment where the bug occurs:
* RPort version 0.9.5
* OS details Debian 11
* User / Client Auth data stored in mysql

**Comment by thorstenkramm** [comment]
@kstieger Thanks for reporting. We have updated the documentation as per your hint.
