### ISSUE TITLE
RPort Plus 0.1.0 not working in versions 0.9.5 and 0.9.6

### ISSUE THREAD

**Issue by lgtbr** [realvnc-labs/rport#909]
**1. Describe the bug**
Hello, RPort Plus plugin version 0.1.0 seems to don't work anymore on 0.9.5 and 0.9.6 versions.

We have followed this instructions : 
[https://kb.rport.io/digging-deeper/rport-plus](https://kb.rport.io/digging-deeper/rport-plus)

But when we restart the service, rportd 
`sudo service rportd status`
`● rportd.service - Create reverse tunnels with ease.`
`     Loaded: loaded (/etc/systemd/system/rportd.service; enabled; vendor preset: enabled)`
`     Active: activating (auto-restart) (Result: exit-code) since Tue 2023-02-14 10:57:24 UTC; 8s ago`
`     Process: 5532 ExecStart=/usr/local/bin/rportd -c /etc/rport/rportd.conf (code=exited, status=1/FAILURE)`
`     Main PID: 5532 (code=exited, status=1/FAILURE)`
`        CPU: 77ms`

`Feb 14 10:57:24 rport-lab systemd[1]: rportd.service: Failed with result 'exit-code'.`

**2. Environment**
RPort version:
0.9.5 & 0.9.6

OS details (Linux distribution, and version or Windows version):
Ubuntu 22.04 LTS

Is rportd running inside a docker container?
No

Are you using a reverse proxy? If yes, which one?
No

**3. Error log**
```
Feb 14 10:55:24 rport-lab rportd[5518]: 2023/02/14 10:55:24 plugin: symbol StartPluginEx not found in plugin github.com/cloudradar-monitoring/rport-plus/cmd/plugin
Feb 14 10:55:24 rport-lab systemd[1]: rportd.service: Main process exited, code=exited, status=1/FAILURE
Feb 14 10:55:24 rport-lab systemd[1]: rportd.service: Failed with result 'exit-code'.
```

**4. rport config file**
```
[plus-plugin]
  ## Rport Plus is a paid for binary extension to Rport. Learn more at https://plus.rport.io/
  plugin_path = "/usr/local/lib/rport/rport-plus.so"

[plus-license]
  # id = "<your-license-id>"
  # key = "<your-license-key>"
  ## An optional web proxy to be used for outbound connections
  # proxy_url = "http://user:pass@proxy.example.com:8080"
```

Before going depper in our tests, we would like to add OAuth to see possibilities with our Azure AD...
Thank you !

**Comment by thorstenkramm** [comment]
@lgtbr I confirm this is a known issue. Shortly (end of February 2023) we will release 0.9.7 to solve this issue.

**Comment by lgtbr** [comment]
> @lgtbr I confirm this is a known issue. Shortly (end of February 2023) we will release 0.9.7 to solve this issue.

Thank you for the reply, we keep an eye on next release

**Comment by thorstenkramm** [comment]
This has been fixed. Starting with 0.9.7 all versions have a corresponding plus version.
