### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by d3al** [realvnc-labs/rport#939]
I'm using rport in a production environment with hundreds of machines and here is a few quality of life features I would like to see.

1. Rport server has an option to perform a webhook upon certain events, maybe make these event types optional to reduce noise.
2. Rport server host tunnel has an option to randomly select an available port and once connected, any reconnections to that host and tunnel will only reuse that port, effectively making that connection a static port going forward as long as the tunnel is active and reactivated in a user configuration period of time through a global setting. Basically treat it like a DHCP server with a reservation and a time limit or set it to forever.
3. I would like to have a library tunnel per client that has an option to auto-reconnect upon that library tunnel not being active. Ensuring that when a client disconnects and comes back up, rport will activate the library tunnel right away.
3. A way to create global library connections and assign to group of machines. So we need need to have a per client library tunnel configuration.

The webhook is great so rport server can notify an api endpoint that a client status has changed. Such as, client disconnected/reconnected, client tunnel destroyed, client tunnel created by user, command created, command sent, schedule command executed etc. Forward via the webhook, hostname, tunnel_id, tunnel_name, tunnel_external_port, tunnel_internal_port, date/time about the event.

Appreciate your consideration.

**Comment by thorstenkramm** [comment]
@d3al 
Your feedback is welcome.
But why did you create a bug report for it?
On creation of a new issue, you get the following message.

> A feature request is not a bug. Feature requests are welcome. Follow [this link](https://github.com/cloudradar-monitoring/rport/discussions/categories/roadmap-feature-wishes-ideas).

Please close your issue and move it to the right place.
