### ISSUE TITLE
rport ui not compatible with iOS

### ISSUE THREAD

**Issue by tnickels** [realvnc-labs/rport#977]
Drop down menu options in the rport web UI are not useable on iOS. You can tap on the drop down menu and all the options appear, however you can not change the selection. I have not tried this via a mouse/trackpad input, but certainly via taping it does not work.

version 0.95

**Comment by bloesss** [comment]
I already mentioned that:

https://github.com/realvnc-labs/rport/issues/743

Very sad to us. In theory, we could offer fast Support by connecting to VNC/SSH/RDP or use commands/simple powershell like "shutdown /r" or "net stop xyz" via Smartphone immediately.

In fact, the GUI is completely unusable on mobile Devices, so we still use Teamviewer.
Thats just a CSS Problem, but I may not do changes to the UI as it is not open source.

**Comment by tnickels** [comment]
thanks. We used different terminology so it didn't appear when I searched.
