### ISSUE TITLE
Issue in creating a tunnel after installing an agent on a remote PC

### ISSUE THREAD

**Issue by abdulbasidh** [realvnc-labs/rport#997]
Whenever I install an agent on a system, I find that I need to restart the system in order to create a tunnel to it. Otherwise, I receive error messages such as **Tunnel destination is not allowed by client configuration** or **Port 5900 is not in listening state**. Despite having installed RDP and VNC servers, I am still encountering this issue. I'm not sure why this is happening and I'm wondering if there is a way to create a tunnel successfully as soon as an agent is installed, without needing to restart the system. Sometimes, even after a long period of inactivity, I face the same issue and need to restart the PCs again to access the tunnel.

**Comment by ataraxia937** [comment]
I find that I can create a tunnel ONCE after installing the client. But if I delete the tunnel, I can't create another one until I restart the client. I get the same two errors as listed above. I'm using the 0.9.5 release.

**Comment by thorstenkramm** [comment]
This issue duplicated. Please [go here](https://github.com/realvnc-labs/rport/issues/898).
