### ISSUE TITLE
Does an official docker image exist?`

### ISSUE THREAD

**Issue by Rez0k** [realvnc-labs/rport#998]
Hi,
Like the topic said, does an official docker image exist?
If not, can you create one?

**Comment by thorstenkramm** [comment]
@Rez0k We don't have a docker image.
And for the moment, we can't create and maintain one. Because RPort has many dependencies (dynamically opened ports, udp communication, SSL certificates, etc.) creating a docker image and the needed documentation is anything but trivial.
